name: Deploy
on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      - run: yarn install
      - run: yarn build
      - uses: cecilapp/gitHub-pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: '<>'
          build_dir: dist
          jekyll: no
